linkPrefix = ""
name = "doxity-simpleton"
version = "1.0.0"
description = "Solidity Documentation"
buildTime = 2017-11-28T18:43:25.538Z
target = "doxity"
src = "contracts/*"
dir = "pages/docs"
out = "docs"
author = "yourname"

[interaction]