linkPrefix = ""
name = "doxity-simpleton"
version = "1.0.0"
description = "Solidity Documentation"
buildTime = 2017-12-01T22:39:20.574Z
target = "doxity"
src = "contracts/*"
dir = "pages/docs"
out = "docs"
author = "yourname"
homepage = "https://tokenbnk.github.io/protocol/"

[interaction]